### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/GitHub-Mate#5]
AS per now the UI doesn't look promising.It has to be improved adopting suitable design principles.

**Comment by devmoses** [comment]
Hi @jamesgeorge007! 
I am @devmoses, a Full-Stack Web developer. I would love to contribute to this project. And I can enhance the UI by adopting sound design principles.

**Comment by jamesgeorge007** [comment]
@devmoses Go ahead :+1:

**Comment by jamesgeorge007** [comment]
@devmoses Make your forks even with upstream since I have committed a merge recently. Also, now the UI part has couple of more elements making it even more cluttered. Hope everything is clear :+1:
